library(data.table)
library(ggmap)
library(shiny)
library(tidyverse)


Murder <- readRDS("C:/Users/sconroy/Documents/DallasPoliceData/Murder.RDS")
Murder[,rowid := 1:.N]
Murder[,Date := as.Date(substr(date1,1,10))]
Murder[,LatLongStart := regexpr("(",geocoded_column,fixed = TRUE)[1] + 1,by = rowid]
Murder[,LatLongEnd := regexpr(")",geocoded_column,fixed = TRUE)[1] - 1,by = rowid]
Murder[,LatLong := substr(geocoded_column,start = LatLongStart,stop = LatLongEnd)]
Murder[,LatLongComma := regexpr(",",LatLong,fixed = TRUE)[1],by = rowid]
Murder[,Latitude := substr(LatLong,start = 1,stop = LatLongComma - 1)]
Murder[,Longitude := substr(LatLong,start = LatLongComma + 1,stop = 1000)]
Murder[,Longitude := as.numeric(Longitude)]
Murder[,Latitude := as.numeric(Latitude)]
Murder[,Year := as.factor(servyr)]
Murder <- Murder[!is.na(Latitude) & !is.na(Longitude) & !is.na(Date) & !is.na(servyr),]


DallasZoom11 <- readRDS("C:/Users/sconroy/Documents/meystingray.github.io/Shiny/Maps/DallasZoom11.RDS")

ui <- fluidPage(
    
    titlePanel("Hello Shiny!"),
    
    sidebarLayout(
        sidebarPanel(
            selectInput("COLUMN", "Filter By:", choices = colnames(Murder)),
            #column(4, selectInput("CONDITION", "Boolean", choices = c("==", "!=", ">", "<"))),
            uiOutput("COL_VALUE"),
            selectInput("COLOR", "Color By:", choices = colnames(Murder))
        ),
        
        # Show text generated by sidebar
        # use text in tidy pipeline to create subsetted dataframe
        mainPanel(
            verbatimTextOutput("as_text"),
            #tableOutput("the_data"),
            plotOutput("plot1")
        )
    )
)

# Define server logic required to draw a histogram
server <- function(input, output) {
    
    output$COL_VALUE <- renderUI({
        x <- Murder %>% select(!!sym(input$COLUMN)) %>% arrange(!!sym(input$COLUMN))
        selectInput("VALUE", "Value", choices = x, selected = x[1])
    })
    
    filtering_string <- reactive ({
        #paste0("filter(Murder, ", input$COLUMN, " ", input$CONDITION, " ", input$VALUE, ")")
        paste0("filter(Murder, ", input$COLUMN, " ", "==", " ", input$VALUE, ")")
    })
    
    output$as_text <- renderText({
        filtering_string()
    })
    
    
    output$the_data <- renderTable({
        eval(parse(text = filtering_string()))
    })
    
    filtered_table <- reactive({
        eval(parse(text = filtering_string()))
    })
    
    output$plot1 <- renderPlot({
        
        #plot(filtered_table()$Sepal.Width, filtered_table()$Sepal.Length, col = "red", lwd = 10)
        colors <- 
            eval(parse(text = paste0("Murder %>% filter(",input$COLUMN," == ",input$VALUE,
                                     ") %>% select(",input$COLOR,") %>% pull(",input$COLOR,")"
                                     )))
        
        ggmap(DallasZoom11,extent = "device") + 
            geom_point(data = Murder[servyr == "2020",], aes(x = Longitude, y = Latitude),fill = colors,
                       size = 2,color = "black",stroke = 1,shape = 21)
        
        #cols <- eval(parse(text = paste0("filtered_table$",input$COLOR)))
        #ggmap(DallasZoom11,extent = "device") + 
        #    geom_point(data = filtered_table(), aes(x = Longitude, y = Latitude),fill = as.factor(colors),
        #               size = 2,color = "black",stroke = 1,shape = 21)
        
        
    })
    
}

# input <- list()
# input$COLUMN <- "servyr"
# input$VALUE <- "2020"
# input$COLOR <- "watch"


# Run the application 
shinyApp(ui = ui, server = server)
